default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight using API Key"
  lane :release do
    match(
      type: "appstore",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      app_identifier: "com.example.caprizon", # Твой Bundle ID
      api_key: app_store_connect_api_key(
        key_id: ENV["APPSTORE_CONNECT_KEY_ID"],
        issuer_id: ENV["APPSTORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"]
      )
    )

    gym(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.example.caprizon" => "match AppStore com.example.caprizon"
        },
        signingStyle: "manual",
        teamID: ENV["APP_STORE_CONNECT_TEAM_ID"]
      }
    )

    deliver(
      ipa: "./Runner.ipa", # Путь куда gym положит .ipa (по умолчанию будет Runner.ipa)
      skip_metadata: true,
      skip_screenshots: true,
      force: true,
      api_key: app_store_connect_api_key(
        key_id: ENV["APPSTORE_CONNECT_KEY_ID"],
        issuer_id: ENV["APPSTORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"]
      )
    )
  end
end
