default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APPSTORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier("com.example.caprizon"),
      git_url: ENV["MATCH_GIT_URL"],
      readonly: false,
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )

    gym(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.example.caprizon" => "match AppStore com.example.caprizon"
        },
        signingStyle: "manual"
      },
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
