name: Build and Upload iOS App

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # <-- укажи свою версию Flutter, если нужна другая

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build IPA with Fastlane gym
        run: |
          mkdir -p fastlane
          cat <<EOF > fastlane/Fastfile
          default_platform(:ios)

          platform :ios do
            desc "Build .ipa for release"
            lane :build do
              gym(
                workspace: "ios/Runner.xcworkspace",
                scheme: "Runner",
                configuration: "Release",
                export_method: "app-store",
                export_options: {
                  signingStyle: "automatic",
                  compileBitcode: true,
                  manageAppVersionAndBuildNumber: false
                },
                skip_codesigning: true
              )
            end
          end
          EOF

          fastlane build

      - name: Upload IPA to TestFlight
        env:
          APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          APPSTORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}
        run: |
          mkdir -p fastlane
          echo "$APPSTORE_CONNECT_PRIVATE_KEY" > fastlane/AuthKey.p8
          KEY_ESCAPED=$(awk '{printf "%s\\n", $0}' fastlane/AuthKey.p8)

          cat <<EOF > fastlane/api_key.json
          {
            "key_id": "${APPSTORE_CONNECT_KEY_ID}",
            "issuer_id": "${APPSTORE_CONNECT_ISSUER_ID}",
            "key": "${KEY_ESCAPED}",
            "in_house": false
          }
          EOF

          fastlane deliver \
            --ipa ./Runner.ipa \
            --api_key_path fastlane/api_key.json \
            --skip_metadata true \
            --skip_screenshots true \
            --force
