name: Build and Upload iOS App

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          zip -r Runner.zip Runner.app
          mv Runner.zip Runner.ipa

      - name: Install Fastlane
        run: gem install fastlane

      - name: Upload to TestFlight
        env:
          APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          APPSTORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}
        run: |
          mkdir -p fastlane
          echo "$APPSTORE_CONNECT_PRIVATE_KEY" > fastlane/AuthKey.p8

          fastlane deliver \
            --ipa build/ios/iphoneos/Runner.ipa \
            --api_key_path fastlane/AuthKey.p8 \
            --api_key_id $APPSTORE_CONNECT_KEY_ID \
            --issuer_id $APPSTORE_CONNECT_ISSUER_ID \
            --skip_metadata true \
            --skip_screenshots true \
            --force
