name: Build and Upload iOS App

on:
  workflow_dispatch:  # ручной запуск по кнопке "Run workflow"

jobs:
  build_and_upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # поменяй на свою версию если надо

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          zip -r Runner.zip Runner.app
          mv Runner.zip Runner.ipa

      - name: Install Fastlane
        run: gem install fastlane

      - name: Upload IPA to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        run: |
          mkdir -p fastlane

          # Сохраняем API Key в формате JSON
          cat <<EOF > fastlane/api_key.json
          {
            "key_id": "${APP_STORE_CONNECT_API_KEY_ID}",
            "issuer_id": "${APP_STORE_CONNECT_ISSUER_ID}",
            "key": "${APP_STORE_CONNECT_API_KEY_CONTENT}",
            "in_house": false
          }
          EOF

          # Загружаем через Fastlane Deliver
          fastlane deliver \
            --ipa build/ios/iphoneos/Runner.ipa \
            --api_key_path fastlane/api_key.json \
            --skip_metadata true \
            --skip_screenshots true \
            --force
