name: Upload IPA to App Store

on:
  workflow_dispatch: # вручную через кнопку "Run workflow" в GitHub

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Download Artifact
        uses: actions/download-artifact@v4.3.1
        with:
          name: ios-release-build
          path: build/ios/iphoneos

      - name: Upload to App Store
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        run: |
          mkdir -p fastlane
          echo "${APP_STORE_CONNECT_API_KEY_CONTENT}" > fastlane/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8
          
          fastlane deliver --ipa build/ios/iphoneos/Runner.ipa \
            --api_key_path fastlane/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8 \
            --api_key_id $APP_STORE_CONNECT_API_KEY_ID \
            --issuer_id $APP_STORE_CONNECT_ISSUER_ID \
            --skip_metadata true \
            --skip_screenshots true \
            --force
